services:
    inertia_symfony.inertia:
        class: Nytodev\InertiaSymfony\Service\InertiaService
        public: true
        arguments:
            $container: '@service_container'
            $twig: '@twig'
            $requestStack: '@request_stack'
            $projectDir: '%kernel.project_dir%'
    Nytodev\InertiaSymfony\Service\InertiaService: '@inertia_symfony.inertia'

    inertia_symfony.gateway:
        class: Nytodev\InertiaSymfony\Ssr\HttpGateway
        public: false
        arguments:
            $container: '@service_container'
            $client: '@http_client'
    Nytodev\InertiaSymfony\Ssr\GatewayInterface: '@inertia_symfony.gateway'

    inertia_symfony.twig_extension:
        class: Nytodev\InertiaSymfony\Twig\InertiaSymfonyTwigExtension
        public: false
        tags:
            - { name: twig.extension }

    inertia_symfony.twig_runtime:
        class: Nytodev\InertiaSymfony\Twig\InertiaSymfonyRuntime
        public: false
        arguments:
            $gateway: '@inertia_symfony.gateway'
        tags:
            - { name: twig.runtime }

    Nytodev\InertiaSymfony\EventListener\InertiaSymfonyListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
        arguments:
            $inertiaService: '@inertia_symfony.inertia'